# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58bcdcdb338a0892fec53328b68f0484865f2e62d77408077a8bdce954299945c43feb08da03686049adba52a73448dcfa0fd77d03cc12f7c4917808905f1bad

test:
  secret_key_base: e7b062dffe058220a9cc3963e275bbaa21f8c926fbec034ac12e1d9f6365707b3b449d52833d9443923d6625129320c429621166078d38dff990ea0627b99662

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
